# Generated by Django 4.2.23 on 2025-08-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_organization_permission_approvalrequest_customrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
