# Generated by Django 4.2.23 on 2025-08-15 17:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(help_text='Unique asset identifier', max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('truck', 'Truck'), ('tractor', 'Tractor'), ('trailer', 'Trailer'), ('van', 'Van'), ('car', 'Car'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, help_text='Department or owner assignment', max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_odometer', models.PositiveIntegerField(default=0, help_text='Current odometer/hour reading')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('out_of_service', 'Out of Service')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_id'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Registration'), ('insurance', 'Insurance'), ('manual', 'Manual'), ('maintenance', 'Maintenance Record'), ('inspection', 'Inspection Report'), ('photo', 'Photo'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='assets/documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
