# Generated by Django 4.2.23 on 2025-08-16 19:52

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, help_text='Main asset image (recommended: 800x600px, max 5MB)', null=True, upload_to=assets.models.asset_image_upload_path),
        ),
        migrations.AddField(
            model_name='asset',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail (150x150px)', null=True, upload_to=assets.models.asset_thumbnail_upload_path),
        ),
    ]
