# Generated by Django 5.0.1 on 2025-08-14 16:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.CharField(help_text='Internal asset number', max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('truck', 'Truck'), ('tractor', 'Tractor'), ('trailer', 'Trailer'), ('van', 'Van'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Pickup Truck'), ('motorcycle', 'Motorcycle'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('vin_number', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_odometer_reading', models.PositiveIntegerField(default=0, help_text='Current mileage/hours')),
                ('fuel_type', models.CharField(blank=True, default='', max_length=30)),
                ('fuel_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('repair', 'In Repair'), ('retired', 'Retired'), ('sold', 'Sold'), ('stolen', 'Stolen/Lost')], default='active', max_length=20)),
                ('condition_rating', models.PositiveIntegerField(blank=True, help_text='Condition rating from 1 (poor) to 10 (excellent)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, default='')),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, default='', max_length=100)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_number'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Registration'), ('insurance', 'Insurance'), ('manual', 'Manual/Documentation'), ('inspection', 'Inspection Certificate'), ('warranty', 'Warranty Information'), ('receipt', 'Purchase Receipt'), ('photo', 'Photo'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='asset_documents/')),
                ('description', models.TextField(blank=True, default='')),
                ('expiry_date', models.DateField(blank=True, help_text='For documents with expiry dates', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet_assets.asset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='asset_images/')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for asset')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fleet_assets.asset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='fleet_assets.department'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['vehicle_type', 'status'], name='fleet_asset_vehicle_c146c8_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['department', 'status'], name='fleet_asset_departm_4bdf01_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['make', 'model'], name='fleet_asset_make_ba0869_idx'),
        ),
    ]
