# Generated by Django 4.2.23 on 2025-08-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverassetassignment',
            options={'ordering': ['priority', '-assigned_date']},
        ),
        migrations.AddField(
            model_name='driverassetassignment',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Assignment priority (1 = highest)'),
        ),
        migrations.AlterField(
            model_name='driverassetassignment',
            name='assignment_type',
            field=models.CharField(choices=[('primary', 'Primary Driver'), ('secondary', 'Secondary Driver'), ('temporary', 'Temporary Assignment'), ('backup', 'Backup Driver'), ('shared', 'Shared Assignment')], default='primary', max_length=20),
        ),
    ]
