# Generated by Django 4.2.23 on 2025-08-16 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_asset_image_asset_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Zone name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Zone description')),
                ('zone_type', models.CharField(choices=[('depot', 'Depot'), ('service_area', 'Service Area'), ('customer_site', 'Customer Site'), ('restricted', 'Restricted Zone'), ('maintenance', 'Maintenance Facility'), ('other', 'Other')], default='other', max_length=20)),
                ('center_lat', models.DecimalField(decimal_places=8, help_text='Zone center latitude', max_digits=10, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('center_lng', models.DecimalField(decimal_places=8, help_text='Zone center longitude', max_digits=11, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('radius', models.FloatField(help_text='Zone radius in meters', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#1976d2', help_text='Hex color code for map display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Zone',
                'verbose_name_plural': 'Location Zones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['zone_type'], name='locations_l_zone_ty_4bd3a6_idx'), models.Index(fields=['is_active'], name='locations_l_is_acti_3d09f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude coordinate (-90.0 to 90.0)', max_digits=10, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude coordinate (-180.0 to 180.0)', max_digits=11, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('timestamp', models.DateTimeField(help_text='When the location was recorded')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('gps_device', 'GPS Device'), ('mobile_app', 'Mobile App'), ('telematics', 'Telematics System')], default='manual', max_length=20)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)])),
                ('address', models.TextField(blank=True, help_text='Human-readable address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Location Update',
                'verbose_name_plural': 'Location Updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetLocationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='assets.asset')),
                ('current_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.locationzone')),
                ('latest_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locationupdate')),
            ],
            options={
                'verbose_name': 'Asset Location Summary',
                'verbose_name_plural': 'Asset Location Summaries',
            },
        ),
        migrations.AddIndex(
            model_name='locationupdate',
            index=models.Index(fields=['asset', '-timestamp'], name='locations_l_asset_i_9b8e63_idx'),
        ),
        migrations.AddIndex(
            model_name='locationupdate',
            index=models.Index(fields=['timestamp'], name='locations_l_timesta_6d7cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='locationupdate',
            index=models.Index(fields=['source'], name='locations_l_source_f16b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlocationsummary',
            index=models.Index(fields=['timestamp'], name='locations_a_timesta_6c609a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlocationsummary',
            index=models.Index(fields=['source'], name='locations_a_source_d7c659_idx'),
        ),
    ]
