# Generated by Django 5.0.1 on 2025-08-18 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationzone',
            name='radius',
            field=models.FloatField(help_text='Zone radius in meters (100m - 50km)', validators=[django.core.validators.MinValueValidator(100.0), django.core.validators.MaxValueValidator(50000.0)]),
        ),
    ]
