# Generated by Django 4.2.23 on 2025-08-20 14:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fiscal_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)])),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_capital_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_capital_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fiscal_year', '-created_at'],
                'permissions': [('view_plan', 'Can view capital plans'), ('edit_plan', 'Can edit capital plans'), ('approve_plan', 'Can approve capital plans'), ('delete_plan', 'Can delete capital plans')],
            },
        ),
        migrations.CreateModel(
            name='CapitalPlanScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('budget_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Positive or negative adjustment to base budget', max_digits=12)),
                ('item_modifications', models.JSONField(default=dict, help_text='Modifications to plan items (quantities, priorities, etc.)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items_included', models.IntegerField(default=0)),
                ('items_deferred', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='capital_planning.capitalplan')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CapitalPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('replacement', 'Asset Replacement'), ('new_purchase', 'New Purchase'), ('upgrade', 'Asset Upgrade'), ('lease', 'Lease')], max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('fleet_asset_id', models.IntegerField(blank=True, help_text='Reference to fleet asset being replaced', null=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('asset_type', models.CharField(max_length=100)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justification', models.TextField(blank=True)),
                ('expected_service_life', models.IntegerField(blank=True, help_text='Expected service life in years', null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_notes', models.TextField(blank=True)),
                ('target_quarter', models.IntegerField(blank=True, help_text='Target quarter for acquisition (1-4)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='capital_planning.capitalplan')),
            ],
            options={
                'ordering': ['priority', '-total_cost'],
            },
        ),
        migrations.CreateModel(
            name='CapitalPlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('department', 'Department Head'), ('finance', 'Finance Review'), ('executive', 'Executive Approval'), ('board', 'Board Approval')], max_length=20)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('request_changes', 'Changes Requested')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True, help_text='Any conditions for approval')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='capital_planning.capitalplan')),
            ],
            options={
                'ordering': ['plan', 'approved_at'],
                'unique_together': {('plan', 'level')},
            },
        ),
    ]
