# Generated by Django 4.2.23 on 2025-08-20 15:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capital_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(max_length=100)),
                ('asset_category', models.CharField(choices=[('building', 'Building'), ('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('infrastructure', 'Infrastructure'), ('technology', 'Technology'), ('other', 'Other')], max_length=50)),
                ('asset_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('installation_date', models.DateField(help_text='Date asset was installed/commissioned')),
                ('expected_useful_life', models.IntegerField(help_text='Expected useful life in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('original_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], default='good', max_length=20)),
                ('last_condition_assessment', models.DateField(blank=True, null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('total_maintenance_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total lifetime maintenance cost', max_digits=10)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_frequency', models.CharField(blank=True, help_text='e.g., Monthly, Quarterly, Annually', max_length=50)),
                ('fleet_asset_id', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_lifecycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_name'],
            },
        ),
        migrations.CreateModel(
            name='CapitalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('replacement', 'Asset Replacement'), ('renovation', 'Renovation/Upgrade'), ('new_construction', 'New Construction'), ('infrastructure', 'Infrastructure'), ('technology', 'Technology'), ('fleet', 'Fleet'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('critical', 'Critical - Immediate'), ('high', 'High - Within 1 Year'), ('medium', 'Medium - 1-3 Years'), ('low', 'Low - 3+ Years')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('scheduled_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)])),
                ('scheduled_quarter', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business_case', models.TextField(help_text='Business justification for the project')),
                ('benefits', models.TextField(help_text='Expected benefits and outcomes')),
                ('risks', models.TextField(blank=True, help_text='Project risks and mitigation strategies')),
                ('project_manager', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('stakeholders', models.TextField(blank=True, help_text='Key stakeholders (comma-separated)')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_capital_projects', to=settings.AUTH_USER_MODEL)),
                ('capital_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_projects', to='capital_planning.capitalplan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_capital_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'scheduled_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('replace', 'Replace'), ('upgrade', 'Upgrade'), ('maintain', 'Maintain'), ('decommission', 'Decommission')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='capital_planning.assetlifecycle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='capital_planning.capitalproject')),
            ],
            options={
                'unique_together': {('project', 'asset_lifecycle')},
            },
        ),
        migrations.AddIndex(
            model_name='capitalproject',
            index=models.Index(fields=['status'], name='capital_pla_status_5ac36e_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalproject',
            index=models.Index(fields=['priority'], name='capital_pla_priorit_834cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalproject',
            index=models.Index(fields=['scheduled_year'], name='capital_pla_schedul_ab2787_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlifecycle',
            index=models.Index(fields=['asset_category'], name='capital_pla_asset_c_f57ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlifecycle',
            index=models.Index(fields=['current_condition'], name='capital_pla_current_ee1c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlifecycle',
            index=models.Index(fields=['installation_date'], name='capital_pla_install_baf1cf_idx'),
        ),
    ]
