# Generated by Django 5.0.1 on 2025-08-14 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interval_type', models.CharField(choices=[('time', 'Time-based (days/months)'), ('mileage', 'Mileage-based'), ('hours', 'Engine Hours-based'), ('manual', 'Manual Schedule')], max_length=10)),
                ('interval_value', models.PositiveIntegerField(help_text='Interval amount (e.g., 30 for 30 days)')),
                ('time_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=10, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('last_service_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, default='', help_text='External vendor if not done in-house', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset', 'maintenance_type__name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('preventive', 'Preventive Maintenance'), ('inspection', 'Inspection'), ('safety', 'Safety Check'), ('compliance', 'Compliance Requirement'), ('seasonal', 'Seasonal Maintenance')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requires_technician', models.BooleanField(default=True)),
                ('requires_parts', models.BooleanField(default=False)),
                ('safety_critical', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, default='', help_text='Step-by-step maintenance instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=0, help_text='Minimum stock level for reorder alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compatible_assets', models.ManyToManyField(blank=True, related_name='compatible_parts', to='fleet_assets.asset')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('unit_cost_at_time', models.DecimalField(decimal_places=2, help_text='Cost per unit at time of use', max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_maintenance.maintenancepart')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('service_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('service_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('technician_notes', models.TextField(blank=True, default='')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('external_cost', models.DecimalField(decimal_places=2, default=0, help_text='Vendor/external costs', max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], default='scheduled', max_length=20)),
                ('quality_rating', models.PositiveIntegerField(blank=True, help_text='Quality rating 1-10', null=True)),
                ('issues_found', models.TextField(blank=True, default='', help_text='Issues discovered during maintenance')),
                ('recommendations', models.TextField(blank=True, default='', help_text='Recommendations for future maintenance')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet_assets.asset')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
