# Generated by Django 5.0.1 on 2025-08-14 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet_assets', '0001_initial'),
        ('fleet_maintenance', '0001_initial'),
        ('fleet_workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='fleet_workorders.workorder'),
        ),
        migrations.AddField(
            model_name='maintenancepartusage',
            name='maintenance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='fleet_maintenance.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='fleet_assets.asset'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_maintenance.maintenanceschedule'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_maintenance.maintenancetype'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_maintenance.maintenancetype'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenancepart',
            unique_together={('part_number', 'manufacturer')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenancepartusage',
            unique_together={('maintenance_record', 'part')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceschedule',
            unique_together={('asset', 'maintenance_type')},
        ),
    ]
